# Generated by Resultant (Test Materialization)
# Source Test Definition: TD-T-ENDPOINT-PATCH-USERS-ID-ROLE
# Do not edit by hand; regenerate via Resultant.

import pytest

@pytest.mark.django_db
def test_td_t_endpoint_patch_users_id_role():
    """Endpoint behavior: PATCH /users/{id}/role

    Test Definition: TD-T-ENDPOINT-PATCH-USERS-ID-ROLE
    Scope: PATCH /users/{id}/role
    Description: As an Event Organiser, I want to make a certain fraction of tickets available for those who want to pay cash for them, so that I don't lose the patronage of a section of potential customers.. Story: As an Event Organiser, I want to make a certain fraction of tickets available for those who want to pay cash for them, so that I don't lose the patronage of a section of potential customers.
Acceptance Criteria:
- The Organiser must be able to choose between selling a fixed number, or a percentage of total available tickets via this channel.
- The Organiser must be able to specify the channel mark-up as a percentage on such tickets.
- The Organiser must be able to specify the hold period for such tickets as a combination of two numbers: (a) the number of hours to hold the ticket, and (b) a timestamp that will serve as a limit on the hold period.
- The system must release all such blocked tickets back to the available pool at the expiry of the earlier of the two criteria specified by the Organiser in AC3.
- The Organiser must be able to choose between a fixed amount per ticket, or a percentage of the ticket cost, as the commission payable to the Location Operator.
- When an Event Attendee pays cash for a ticket to a Location Operator, a database entry must be made containing the Event ID, Ticket ID, Location Operator ID, Timestamp, Amount collected and the Computed Commission to facilitate audit and reconciliation.
    """
    try:
        from django.test import Client
    except Exception as exc:  # pragma: no cover
        pytest.fail('django.test.Client unavailable; ensure Django is installed and DJANGO_SETTINGS_MODULE is set')

    client = Client()
    url = '/users/1/role'
    resp = client.patch(url, data={}, content_type='application/json')
    if resp.status_code == 404 and not url.startswith('/api/'):
        resp = client.patch('/api' + url, data={}, content_type='application/json')
    assert resp.status_code == 200, 'Expected 200 for PATCH /users/{id}/role; got %s' % resp.status_code
