# Generated by Resultant (Test Materialization)
# Source Test Definition: TD-T-ENDPOINT-PATCH-API-V1-RESOURCE-ID
# Do not edit by hand; regenerate via Resultant.

import pytest

@pytest.mark.django_db
def test_td_t_endpoint_patch_api_v1_resource_id():
    """Endpoint behavior: PATCH /api/v1/resource/{id}

    Test Definition: TD-T-ENDPOINT-PATCH-API-V1-RESOURCE-ID
    Scope: PATCH /api/v1/resource/{id}
    Description: Harden order pricing rounding so missing totals don't 500 (ADV-49: round_decimal None input). # Harden order pricing rounding so missing totals don't 500 (ADV-49: round_decimal None input)

The order pricing path uses the round_decimal helper in src/pretix/base. When a pricing or tax field is missing (None) — e.g. an optional discount or tax override left empty — round_decimal raises a TypeError and the PATCH /api/v1/resource/{id} order endpoint returns a 500 instead of handling it gracefully. Harden the rounding in the pricing serializer so None totals are treated as 0.00.

Acceptance Criteria:
- round_decimal in src/pretix/base returns Decimal('0.00') when passed None or an empty value instead of raising
- The order pricing serializer in src/pretix/api/serializers rounds missing price fields to 0.00 before validation
- PATCH /api/v1/resource/{id} returns 200 (not 500) when an optional price/tax field is omitted
- Existing valid numeric prices keep their current rounding behavior and precision
- A unit test covers the None-input path for round_decimal and the omitted-price request
    """
    try:
        from django.test import Client
    except Exception as exc:  # pragma: no cover
        pytest.fail('django.test.Client unavailable; ensure Django is installed and DJANGO_SETTINGS_MODULE is set')

    client = Client()
    url = '/api/v1/resource/1'
    resp = client.patch(url, data={}, content_type='application/json')
    if resp.status_code == 404 and not url.startswith('/api/'):
        resp = client.patch('/api' + url, data={}, content_type='application/json')
    assert resp.status_code == 200, 'Expected 200 for PATCH /api/v1/resource/{id}; got %s' % resp.status_code

    url = '/api/v1/resource/1'
    resp = client.patch(url, data={}, content_type='application/json')
    if resp.status_code == 404 and not url.startswith('/api/'):
        resp = client.patch('/api' + url, data={}, content_type='application/json')
    assert resp.status_code == 500, 'Expected 500 for PATCH /api/v1/resource/{id}; got %s' % resp.status_code
